"""The three-layer certificate stack (N3-N6).

Layer 1: exact algebraic bounds (Lipschitz products, per-family pruning errors).
Layer 2: SOS local boxes (2a) + Lyapunov-margin degradation curve (2b).
Layer 3: STL robustness tails via IQAE vs RESTART+GEV vs MC, closed by
         scenario-optimization + conformal calibration.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from pathlib import Path


@dataclass
class LipschitzRow:
    """One row of the Layer-1 certificate table (N3)."""
    layer: str
    pareto_ratio: float
    lipschitz: float
    input_box_diam: float
    certified_safe_set_pct: float


class CertificateStore:
    """JSON exporters so the report tables are generated by the package."""

    def __init__(self, cert_dir: Path):
        self.cert_dir = cert_dir
        self.cert_dir.mkdir(parents=True, exist_ok=True)

    def write_lipschitz_table(self, rows: list[LipschitzRow]) -> Path:
        path = self.cert_dir / "lipschitz_table.json"
        path.write_text(json.dumps([asdict(r) for r in rows], indent=2))
        return path


# Layer 2/3 interfaces (implementations land with N4-N6).
def sos_boxes():
    raise NotImplementedError("SOS boxes land with the Julia toolchain pin (Q22).")


def lyapunov_survival_curve():
    raise NotImplementedError("Lyapunov curve + predictor lands with N5.")
